services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: ${DB_CONTAINER_NAME:-articles-assistant-db}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-articles-assistant}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ${REDIS_CONTAINER_NAME:-articles-assistant-redis}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes

volumes:
  pgdata:
  redisdata:
